### ISSUE TITLE
Export existing schema with MysqlWorkbench

### ISSUE THREAD

**Issue by WhiteBoardDev** [SlurpyTurts/bcc-db#3]
The current files in this repo wont work for spinning up a new DB. We need to be able to re-create the database when slurpy's computer falls into a ditch.

This work should be after #4 because it has to be ran on an existing database. We will be able to use the mysql workbench "reverse engineer" feature on an existing database in order to extract a model and schema.

Once we have a model checked into source control, it will be really easy to upgrade existing database installations and also create new ones using the model as the master version of the schema. 

1) Download and install mysql workbench http://www.mysql.com/products/workbench/
2) Use the reverse engineer option to extract your schema https://www.youtube.com/watch?v=xIzRivkXGE8
3) The output of the reverse engineering process will be a MySql model. File->Save this model as bcc-model in this repo
4) From now, every time you want to change the DB, make changes to this model first. Then use MySql workbench to apply the model to a running database. This way anyone can create and update their databases from the same model.

I can take this work on after #4 is completed.

**Comment by WhiteBoardDev** [comment]
Depends on #4

**Comment by srt4** [comment]
Schema: https://github.com/SlurpyTurts/bcc-db/blob/master/BCC.mwb
