### ISSUE TITLE
Database dump of current DB

### ISSUE THREAD

**Issue by WhiteBoardDev** [SlurpyTurts/bcc-db#4]
The current files in this repo are not enough to spin up a new database. We need to create a database dump of the current DB running on Slurpy's computer. @SlurpyTurts please do the following

1) install mysql workbench http://www.mysql.com/products/workbench/
2) make sure mysql is running locally
3) run mysql workbench and connect to the local DB
4) Click Server-> Data Export
5) A data export screen will appear
6) Select the BCC database to export
7) toward the bottom of the screen there is a selection called  "Export to dump project folder" please use this repo folder as the destination
8) check the box titled "Include create schema"
9) run the export

Now make sure to check in the database dump

`git commit -a -m "Adding database dump"`
`git push`

**Comment by srt4** [comment]
DB dump is added under bcc-db/bcc-dump
